### ISSUE TITLE
Command line install/config instructions

### ISSUE THREAD

**Issue by jjv5** [pinellolab/CRISPR-SURF#2]
Any possibility of some documentation for installing the command line version outside of docker?

**Comment by lucapinello** [comment]
Hi there, at the moment we have no plan to extend this to a standalone Python package. There are some tricky dependencies so we preferred to provide the Docker version. If you are trying to run this on an HPC cluster where docker is not allowed, you can consider using Singularity: https://singularity.lbl.gov/docs-docker
